from flask import Flask, request, render_template, jsonify
from src.pipeline.prediction_pipeline import CustomData, PredictPipeline

application = Flask(__name__)
app = application
States_List={'Andaman and Nicobar Islands': ['NICOBARS',
  'Andaman and Nicobar Islands',
  'SOUTH ANDAMANS',
  'NORTH AND MIDDLE ANDAMAN'],
 'Andhra Pradesh': ['KHAMMAM',
  'EAST GODAVARI',
  'MEDAK',
  'ADILABAD',
  'WEST GODAVARI',
  'RANGAREDDI',
  'ANANTAPUR',
  'SPSR NELLORE',
  'WARANGAL',
  'KRISHNA',
  'GUNTUR',
  'SRIKAKULAM',
  'VIZIANAGARAM',
  'KADAPA',
  'NALGONDA',
  'HYDERABAD',
  'VISAKHAPATANAM',
  'CHITTOOR',
  'KARIMNAGAR',
  'MAHBUBNAGAR',
  'NIZAMABAD',
  'KURNOOL',
  'PRAKASAM'],
 'Arunachal Pradesh': ['TIRAP',
  'CHANGLANG',
  'LONGDING',
  'LOHIT',
  'EAST SIANG',
  'SIANG',
  'PAPUM PARE',
  'KRA DAADI',
  'LOWER SUBANSIRI',
  'LOWER DIBANG VALLEY',
  'TAWANG',
  'PAKKE KESSANG',
  'LOWER SIANG',
  'KURUNG KUMEY',
  'NAMSAI',
  'LEPARADA',
  'WEST SIANG',
  'SHI YOMI',
  'ANJAW',
  'DIBANG VALLEY',
  'EAST KAMENG',
  'UPPER SIANG',
  'WEST KAMENG',
  'KAMLE',
  'UPPER SUBANSIRI'],
 'Assam': ['SOUTH SALMARA MANCACHAR',
  'DIMA HASAO',
  'DHEMAJI',
  'BISWANATH',
  'KARBI ANGLONG',
  'HOJAI',
  'NALBARI',
  'CHARAIDEO',
  'TINSUKIA',
  'BAKSA',
  'KAMRUP',
  'BONGAIGAON',
  'KARIMGANJ',
  'SIVASAGAR',
  'LAKHIMPUR',
  'KOKRAJHAR',
  'MARIGAON',
  'DARRANG',
  'BARPETA',
  'KAMRUP METRO',
  'CACHAR',
  'MAJULI',
  'WEST KARBI ANGLONG',
  'CHIRANG',
  'SONITPUR',
  'GOLAGHAT',
  'JORHAT',
  'HAILAKANDI',
  'GOALPARA',
  'UDALGURI',
  'NAGAON',
  'DIBRUGARH',
  'DHUBRI'],
 'Bihar': ['PATNA',
  'GODDA',
  'KATIHAR',
  'JAMUI',
  'GAYA',
  'BANKA',
  'CHATRA',
  'ARARIA',
  'KHAGARIA',
  'DHANBAD',
  'PAKUR',
  'SHEOHAR',
  'BEGUSARAI',
  'SIWAN',
  'DUMKA',
  'NALANDA',
  'HAZARIBAGH',
  'BUXAR',
  'BHOJPUR',
  'BOKARO',
  'GIRIDIH',
  'PALAMU',
  'DARBHANGA',
  'GOPALGANJ',
  'MUNGER',
  'ARWAL',
  'NAWADA',
  'GUMLA',
  'SAMASTIPUR',
  'ROHTAS',
  'KISHANGANJ',
  'RANCHI',
  'MADHEPURA',
  'SUPAUL',
  'SAHARSA',
  'VAISHALI',
  'SARAN',
  'PURBI CHAMPARAN',
  'LOHARDAGA',
  'SHEIKHPURA',
  'SITAMARHI',
  'BHAGALPUR',
  'PASHCHIM CHAMPARAN',
  'SAHEBGANJ',
  'EAST SINGHBUM',
  'AURANGABAD',
  'LAKHISARAI',
  'DEOGHAR',
  'JEHANABAD',
  'KODERMA',
  'MUZAFFARPUR',
  'WEST SINGHBHUM',
  'GARHWA',
  'PURNIA',
  'MADHUBANI',
  'KAIMUR (BHABUA)'],
 'Chandigarh': ['CHANDIGARH'],
 'Chhattisgarh': ['BASTAR',
  'RAJNANDGAON',
  'JASHPUR',
  'KORBA',
  'BALOD',
  'MUNGELI',
  'SUKMA',
  'BALRAMPUR',
  'DHAMTARI',
  'BEMETARA',
  'KONDAGAON',
  'DURG',
  'BALODA BAZAR',
  'KANKER',
  'KOREA',
  'RAIPUR',
  'SURGUJA',
  'BIJAPUR',
  'NARAYANPUR',
  'DANTEWADA',
  'KABIRDHAM',
  'GARIYABAND',
  'BILASPUR',
  'SURAJPUR',
  'MAHASAMUND',
  'GAURELLA-PENDRA-MARWAHI',
  'JANJGIR-CHAMPA',
  'RAIGARH'],
 'Dadra and Nagar Haveli': ['DADRA AND NAGAR HAVELI'],
 'Daman and Diu': ['DIU', 'DAMAN', 'Daman and Diu'],
 'Delhi': ['DELHI_TOTAL', 'Delhi'],
 'Goa': ['SOUTH GOA', 'NORTH GOA', 'Goa'],
 'Gujarat': ['AHMADABAD',
  'BANAS KANTHA',
  'SURENDRANAGAR',
  'JUNAGADH',
  'GANDHINAGAR',
  'SABAR KANTHA',
  'GIR SOMNATH',
  'ANAND',
  'BOTAD',
  'KHEDA',
  'DEVBHUMI DWARKA',
  'ARAVALLI',
  'PORBANDAR',
  'MORBI',
  'DOHAD',
  'NAVSARI',
  'CHHOTAUDEPUR',
  'NARMADA',
  'TAPI',
  'BHARUCH',
  'VADODARA',
  'AMRELI',
  'DANG',
  'SURAT',
  'KACHCHH',
  'MAHISAGAR',
  'JAMNAGAR',
  'MAHESANA',
  'VALSAD',
  'BHAVNAGAR',
  'PANCH MAHALS',
  'RAJKOT',
  'PATAN'],
 'Haryana': ['JHAJJAR',
  'SONIPAT',
  'MAHENDRAGARH',
  'ROHTAK',
  'PANCHKULA',
  'KARNAL',
  'HISAR',
  'PALWAL',
  'GURGAON',
  'AMBALA',
  'REWARI',
  'CHARKI DADRI',
  'YAMUNANAGAR',
  'KURUKSHETRA',
  'FARIDABAD',
  'BHIWANI',
  'SIRSA',
  'KAITHAL',
  'PANIPAT',
  'FATEHABAD',
  'MEWAT',
  'JIND'],
 'Himachal Pradesh': ['LAHUL AND SPITI',
  'KULLU',
  'SIRMAUR',
  'BILASPUR',
  'CHAMBA',
  'KANGRA',
  'HAMIRPUR',
  'MANDI',
  'UNA',
  'KINNAUR',
  'SHIMLA',
  'SOLAN'],
 'Jammu and Kashmir': ['JAMMU',
  'RAJAURI',
  'BARAMULLA',
  'SHOPIAN',
  'SRINAGAR',
  'LEH LADAKH',
  'POONCH',
  'GANDERBAL',
  'ANANTNAG',
  'KATHUA',
  'PULWAMA',
  'REASI',
  'BADGAM',
  'KUPWARA',
  'UDHAMPUR',
  'KULGAM',
  'RAMBAN',
  'BANDIPORA',
  'KARGIL',
  'KISHTWAR',
  'DODA',
  'SAMBA'],
 'Jharkhand': ['GODDA',
  'CHATRA',
  'PAKUR',
  'DHANBAD',
  'DUMKA',
  'HAZARIBAGH',
  'BOKARO',
  'GIRIDIH',
  'SARAIKELA KHARSAWAN',
  'GUMLA',
  'RANCHI',
  'LOHARDAGA',
  'SAHEBGANJ',
  'SIMDEGA',
  'EAST SINGHBUM',
  'DEOGHAR',
  'LATEHAR',
  'KODERMA',
  'WEST SINGHBHUM',
  'GARHWA',
  'JAMTARA',
  'PALAMU',
  'KHUNTI',
  'RAMGARH'],
 'Karnataka': ['KOPPAL',
  'TUMKUR',
  'BAGALKOT',
  'RAMANAGARA',
  'CHIKBALLAPUR',
  'GADAG',
  'CHAMARAJANAGARA',
  'YADAGIRI',
  'BALLARI',
  'KODAGU',
  'RAICHUR',
  'SHIMOGA',
  'CHIKKAMAGALURU',
  'UTTAR KANNAD',
  'DAVANGERE',
  'BANGALORE RURAL',
  'BELLARY',
  'VIJAYAPURA',
  'GULBARGA',
  'UTTARA KANNADA',
  'BAGALKOTE',
  'HAVERI',
  'BELGAUM',
  'KOLAR',
  'TUMAKURU',
  'UDUPI',
  'YADGIR',
  'MYSORE',
  'DAKSHIN KANNAD',
  'BIJAPUR',
  'CHITRADURGA',
  'BIDAR',
  'DAKSHINA KANNADA',
  'SHIVAMOGGA',
  'KALABURAGI',
  'BELAGAVI',
  'DHARWAD',
  'MYSURU',
  'CHIKKABALLAPURA',
  'CHIKMAGALUR',
  'HASSAN',
  'MANDYA',
  'BENGALURU URBAN',
  'CHAMARAJANAGAR'],
 'Kerala': ['PATHANAMTHITTA',
  'KANNUR',
  'ALAPPUZHA',
  'ERNAKULAM',
  'KASARAGOD',
  'THRISSUR',
  'KOLLAM',
  'WAYANAD',
  'KOTTAYAM',
  'IDUKKI',
  'PALAKKAD',
  'MALAPPURAM',
  'THIRUVANANTHAPURAM',
  'KOZHIKODE'],
 'Madhya Pradesh': ['BASTAR',
  'RAJNANDGAON',
  'RAJGARH',
  'DHAR',
  'HARDA',
  'ANUPPUR',
  'MANDSAUR',
  'RAISEN',
  'TIKAMGARH',
  'KHANDWA',
  'DEWAS',
  'JASHPUR',
  'BHIND',
  'BARWANI',
  'KORBA',
  'DATIA',
  'SEHORE',
  'SIDHI',
  'SHAJAPUR',
  'NIWARI',
  'CHHINDWARA',
  'SHAHDOL',
  'ALIRAJPUR',
  'AGAR MALWA',
  'DHAMTARI',
  'JABALPUR',
  'MORENA',
  'PANNA',
  'SHEOPUR',
  'RATLAM',
  'NARSINGHPUR',
  'BHOPAL',
  'DURG',
  'REWA',
  'CHHATARPUR',
  'KANKER',
  'BURHANPUR',
  'GUNA',
  'NEEMUCH',
  'KATNI',
  'BETUL',
  'KHARGONE',
  'SATNA',
  'INDORE',
  'KOREA',
  'RAIPUR',
  'SEONI',
  'SURGUJA',
  'UJJAIN',
  'HOSHANGABAD',
  'DANTEWADA',
  'GWALIOR',
  'SINGRAULI',
  'JHABUA',
  'UMARIA',
  'MANDLA',
  'SHIVPURI',
  'KABIRDHAM',
  'SAGAR',
  'BILASPUR',
  'DINDORI',
  'DAMOH',
  'VIDISHA',
  'MAHASAMUND',
  'JANJGIR-CHAMPA',
  'ASHOKNAGAR',
  'BALAGHAT'],
 'Maharashtra': ['JALGAON',
  'SATARA',
  'AHMEDNAGAR',
  'YAVATMAL',
  'RATNAGIRI',
  'SINDHUDURG',
  'WARDHA',
  'GONDIA',
  'WASHIM',
  'MUMBAI SUBURBAN',
  'SOLAPUR',
  'MUMBAI',
  'BHANDARA',
  'RAIGAD',
  'AMRAVATI',
  'PALGHAR',
  'PUNE',
  'CHANDRAPUR',
  'NASHIK',
  'NAGPUR',
  'LATUR',
  'NANDURBAR',
  'BULDHANA',
  'AKOLA',
  'KOLHAPUR',
  'THANE',
  'BEED',
  'AURANGABAD',
  'PARBHANI',
  'GADCHIROLI',
  'SANGLI',
  'HINGOLI',
  'OSMANABAD',
  'NANDED',
  'JALNA',
  'DHULE'],
 'Manipur': ['CHANDEL',
  'TAMENGLONG',
  'SENAPATI',
  'THOUBAL',
  'BISHNUPUR',
  'IMPHAL WEST',
  'UKHRUL',
  'CHURACHANDPUR',
  'IMPHAL EAST'],
 'Meghalaya': ['WEST KHASI HILLS',
  'NORTH GARO HILLS',
  'EAST GARO HILLS',
  'SOUTH WEST GARO HILLS',
  'WEST JAINTIA HILLS',
  'RI BHOI',
  'EAST KHASI HILLS',
  'EAST JAINTIA HILLS',
  'SOUTH WEST KHASI HILLS',
  'WEST GARO HILLS',
  'SOUTH GARO HILLS'],
 'Mizoram': ['MAMIT',
  'CHAMPHAI',
  'KOLASIB',
  'LAWNGTLAI',
  'AIZAWL',
  'SAIHA',
  'SERCHHIP',
  'LUNGLEI'],
 'Nagaland': ['TUENSANG',
  'ZUNHEBOTO',
  'KIPHIRE',
  'WOKHA',
  'DIMAPUR',
  'LONGLENG',
  'KOHIMA',
  'MON',
  'PEREN',
  'MOKOKCHUNG',
  'PHEK'],
 'Odisha': ['DHENKANAL',
  'SAMBALPUR',
  'SONEPUR',
  'BALESHWAR',
  'BHADRAK',
  'KALAHANDI',
  'JAJAPUR',
  'KENDRAPARA',
  'NAYAGARH',
  'NUAPADA',
  'GAJAPATI',
  'GANJAM',
  'ANUGUL',
  'BOUDH',
  'KHORDHA',
  'SUNDARGARH',
  'MAYURBHANJ',
  'KORAPUT',
  'JHARSUGUDA',
  'MALKANGIRI',
  'NABARANGPUR',
  'CUTTACK',
  'PURI',
  'BALANGIR',
  'KENDUJHAR',
  'BARGARH',
  'JAGATSINGHAPUR',
  'DEOGARH',
  'RAYAGADA',
  'KANDHAMAL'],
 'Puducherry': ['MAHE', 'PONDICHERRY', 'YANAM', 'KARAIKAL'],
 'Punjab': ['SHAHID BHAGAT SINGH NAGAR',
  'BARNALA',
  'MOGA',
  'FATEHGARH SAHIB',
  'PATHANKOT',
  'TARN TARAN',
  'S',
  'JALANDHAR',
  'FIROZEPUR',
  'GURDASPUR',
  'MANSA',
  'PATIALA',
  'SANGRUR',
  'RUPNAGAR',
  'MUKTSAR',
  'AMRITSAR',
  'FARIDKOT',
  'BATHINDA',
  'LUDHIANA',
  'FAZILKA',
  'NAWANSHAHR',
  'HOSHIARPUR',
  'KAPURTHALA'],
 'Rajasthan': ['KOTA',
  'DAUSA',
  'DUNGARPUR',
  'SAWAI MADHOPUR',
  'DHOLPUR',
  'JAISALMER',
  'JAIPUR',
  'NAGAUR',
  'AJMER',
  'PALI',
  'JHUNJHUNU',
  'KARAULI',
  'JODHPUR',
  'BANSWARA',
  'SIROHI',
  'JHALAWAR',
  'BHILWARA',
  'BARMER',
  'BHARATPUR',
  'HANUMANGARH',
  'BIKANER',
  'UDAIPUR',
  'JALORE',
  'SIKAR',
  'RAJSAMAND',
  'BARAN',
  'CHURU',
  'CHITTORGARH',
  'ALWAR',
  'GANGANAGAR',
  'BUNDI',
  'TONK',
  'PRATAPGARH'],
 'Sikkim': ['WEST DISTRICT',
  'EAST DISTRICT',
  'SOUTH DISTRICT',
  'NORTH DISTRICT'],
 'Tamil Nadu': ['THIRUVALLUR',
  'ARIYALUR',
  'COIMBATORE',
  'TIRUNELVELI',
  'TUTICORIN',
  'CHENNAI',
  'TIRUCHIRAPPALLI',
  'VIRUDHUNAGAR',
  'TIRUPPUR',
  'RAMANATHAPURAM',
  'DINDIGUL',
  'KANNIYAKUMARI',
  'THE NILGIRIS',
  'TENKASI',
  'TIRUVANNAMALAI',
  'VELLORE',
  'PERAMBALUR',
  'NAMAKKAL',
  'CHENGALPATTU',
  'RANIPET',
  'VILLUPURAM',
  'THENI',
  'KALLAKURICHI',
  'KARUR',
  'KRISHNAGIRI',
  'TIRUPATHUR',
  'NAGAPATTINAM',
  'THANJAVUR',
  'PUDUKKOTTAI',
  'SALEM',
  'THOOTHUKUDI',
  'THIRUVARUR',
  'MADURAI',
  'CUDDALORE',
  'SIVAGANGA',
  'KANCHIPURAM',
  'ERODE',
  'DHARMAPURI'],
 'Tripura': ['KHOWAI',
  'SEPAHIJALA',
  'UNAKOTI',
  'GOMATI',
  'NORTH TRIPURA',
  'WEST TRIPURA',
  'SOUTH TRIPURA',
  'DHALAI'],
 'Uttar Pradesh': ['SITAPUR',
  'AMROHA',
  'BARABANKI',
  'CHAMOLI',
  'CHITRAKOOT',
  'BANDA',
  'KANPUR NAGAR',
  'BUDAUN',
  'BALRAMPUR',
  'GAUTAM BUDDHA NAGAR',
  'HAPUR',
  'MAHOBA',
  'TEHRI GARHWAL',
  'KASGANJ',
  'UTTAR KASHI',
  'GONDA',
  'DEHRADUN',
  'PITHORAGARH',
  'SHAMLI',
  'BAHRAICH',
  'ETAWAH',
  'CHANDAULI',
  'BASTI',
  'JHANSI',
  'DEORIA',
  'LUCKNOW',
  'PRATAPGARH',
  'HATHRAS',
  'SIDDHARTH NAGAR',
  'ALLAHABAD',
  'FARRUKHABAD',
  'AMBEDKAR NAGAR',
  'AMETHI',
  'AGRA',
  'MAU',
  'JALAUN',
  'FATEHPUR',
  'JAUNPUR',
  'BIJNOR',
  'BULANDSHAHR',
  'SANT RAVIDAS NAGAR',
  'KHERI',
  'RAE BARELI',
  'UDAM SINGH NAGAR',
  'ALIGARH',
  'HARDOI',
  'SANT KABEER NAGAR',
  'BALLIA',
  'PILIBHIT',
  'HARIDWAR',
  'MORADABAD',
  'GORAKHPUR',
  'SONBHADRA',
  'BAGHPAT',
  'GHAZIPUR',
  'SAHARANPUR',
  'MEERUT',
  'MUZAFFARNAGAR',
  'LALITPUR',
  'PAURI GARHWAL',
  'FAIZABAD',
  'SHRAVASTI',
  'RAMPUR',
  'BAGESHWAR',
  'MIRZAPUR',
  'VARANASI',
  'AZAMGARH',
  'UNNAO',
  'FIROZABAD',
  'MAHARAJGANJ',
  'ETAH',
  'SAMBHAL',
  'GHAZIABAD',
  'BAREILLY',
  'NAINITAL',
  'RUDRA PRAYAG',
  'MATHURA',
  'KUSHI NAGAR',
  'AURAIYA',
  'HAMIRPUR',
  'KANPUR DEHAT',
  'MAINPURI',
  'KANNAUJ',
  'KAUSHAMBI',
  'CHAMPAWAT',
  'SULTANPUR',
  'SHAHJAHANPUR',
  'ALMORA'],
 'Uttarakhand': ['UTTAR KASHI',
  'HARIDWAR',
  'CHAMOLI',
  'DEHRADUN',
  'BAGESHWAR',
  'PITHORAGARH',
  'UDAM SINGH NAGAR',
  'TEHRI GARHWAL',
  'PAURI GARHWAL',
  'CHAMPAWAT',
  'NAINITAL',
  'RUDRA PRAYAG',
  'ALMORA'],
 'West Bengal': ['MEDINIPUR EAST',
  '24 PARAGANAS NORTH',
  'BIRBHUM',
  '24 PARAGANAS SOUTH',
  'DINAJPUR UTTAR',
  'HOOGHLY',
  'HOWRAH',
  'NADIA',
  'MURSHIDABAD',
  'DINAJPUR DAKSHIN',
  'JHARGRAM',
  'PASCHIM BARDHAMAN',
  'DARJEELING',
  'KALIMPONG',
  'COOCHBEHAR',
  'MEDINIPUR WEST',
  'PURULIA',
  'BANKURA',
  'JALPAIGURI',
  'MALDAH',
  'ALIPURDUAR',
  'PURBA BARDHAMAN'],
 'Telangana': ['VIKARABAD',
  'DADRA AND NAGAR HAVELI',
  'NARAYANAPET',
  'KHAMMAM',
  'SURYAPET',
  'YADADRI',
  'DIU',
  'SIDDIPET',
  'MEDAK',
  'NAGARKURNOOL',
  'ADILABAD',
  'JAGITIAL',
  'RANGAREDDI',
  'MANCHERIAL',
  'KAMAREDDY',
  'MEDCHAL MALKAJGIRI',
  'SANGAREDDY',
  'RAJANNA',
  'WARANGAL',
  'JANGOAN',
  'WARANGAL URBAN',
  'PEDDAPALLI',
  'MULUGU',
  'NIRMAL',
  'JAYASHANKAR',
  'DAMAN',
  'NALGONDA',
  'MAHABUBABAD',
  'WANAPARTHY',
  'JOGULAMBA',
  'KARIMNAGAR',
  'MAHBUBNAGAR',
  'NIZAMABAD',
  'MEDCHAL',
  'HANUMAKONDA',
  'KOMARAM BHEEM ASIFABAD',
  'BHADRADRI'],
 'Laddakh': ['KARGIL']}

crops = [
    'Arecanut', 'Banana', 'Black pepper', 'Cashewnut', 'Coconut',
    'Dry chillies', 'Ginger', 'Other Kharif pulses', 'other oilseeds',
    'Rice', 'Sugarcane', 'Sweet potato', 'Arhar/Tur', 'Bajra',
    'Castor seed', 'Coriander', 'Cotton(lint)', 'Gram', 'Groundnut',
    'Horse-gram', 'Jowar', 'Linseed', 'Maize', 'Mesta',
    'Moong(Green Gram)', 'Niger seed', 'Onion', 'Other Rabi pulses',
    'Potato', 'Ragi', 'Rapeseed &Mustard', 'Safflower', 'Sesamum',
    'Small millets', 'Soyabean', 'Sunflower', 'Tapioca', 'Tobacco',
    'Turmeric', 'Urad', 'Wheat', 'Oilseeds total', 'Jute', 'Masoor',
    'Peas & beans (Pulses)', 'Barley', 'Garlic', 'Khesari', 'Sannhamp',
    'Guar seed', 'Moth', 'Cardamom', 'Other Cereals', 'Cowpea(Lobia)',
    'Dry Ginger', 'Other Summer Pulses'
]

seasons = [
    'Kharif', 'Whole Year', 'Rabi', 'Autumn', 'Summer', 'Winter'
]

@app.route('/')
def home_page():
    states = list(States_List.keys())  # Extracting keys from States_List
    return render_template('index.html', states=states, crops=crops, seasons=seasons)

@app.route('/predict', methods=['GET', 'POST'])
def predict_datapoint(): 
    if request.method == "GET": 
                return render_template("form.html", crops=crops, seasons=seasons)
    else: 
        data = CustomData(
            state=request.form.get('state'),
            district=request.form.get('district'),
            crop=request.form.get("crop"), 
            year=int(request.form.get("year")), 
            season=request.form.get("season"),
            area=float(request.form.get("area")), 
            production=float(request.form.get("production")), 
        )
        new_data = data.get_data_as_dataframe()
        predict_pipeline = PredictPipeline()
        pred = predict_pipeline.predict(new_data)

        results = round(pred[0], 2)

        return render_template("results.html", final_result=(str(results)+" Tonnes"))
    
@app.route('/get_districts', methods=['POST'])
def get_districts():
    selected_state = request.form.get('state')
    if selected_state in States_List:
        districts = States_List[selected_state]
        return jsonify({'districts': districts})
    else:
        return jsonify({'districts': []})
    
if __name__ == "__main__": 
    app.run(host="0.0.0.0", debug=True)